### ISSUE TITLE
Add ability to increase UI font size

### ISSUE THREAD

**Issue by Ruffz** [casperstorm/ajour#100]
_**Is your feature request related to a problem? Please describe.**_
UI font size is a little too tiny.

_**Describe the solution you'd like**_
Add ability to increase UI font size.

**Comment by mlablah** [comment]
@Ruffz I like this idea and I agree with you that the default font size can be a little small in the Windows build of Ajour!

In this case however, I think the right solution would be to give the user full UI zoom control, and not just control of the font size, since the latter may have unforeseen consequences with the layout of the UI breaking.

I have therefore added UI zoom to the backlog of our [roadmap](https://github.com/casperstorm/ajour/projects/2#card-45378181) where you can keep track of its progress. 

Closing this issue as the feature is now on our backlog.
