### ISSUE TITLE
Elvui Add-on folder is deleted if an error is encountered during the update process.

### ISSUE THREAD

**Issue by hamdeli** [casperstorm/ajour#107]
**Describe the bug**
 Specific add-on's app folder is deleted after failure to update due to permissions replacing existing files.

**To Reproduce**
Steps to reproduce the behavior\:
_Requires an older version of ElvUI to be manually installed so as to trigger the update availability prompt in Ajour._
1. Launch Ajour normally, no elevated permissions.
2. Take note of add-count.
3. Click to update ElvUI.
4. If error is encountered, "access denied 5" for example, add-on count decrements.
5. Add-on is no longer present in the addons folder of WoW.

**Expected behavior**
Add-on folder that failed to update should not be deleted. It should be rolled back to its current version.
According to the source, it may be working as designed in the current version.

**Desktop:**
 - OS: [Windows 10 Pro]
 - OS Version: [1909]
 - OS Build: [18363.1082] 

**Additional context**
ElvUI updates prior to using Ajour were managed manually (not part of curse-forge). This is only happening in retail version. I have only reproduced this issue with ElvUI in retail.

**Comment by hamdeli** [comment]
Label should be changed to "enhancement"

**Comment by mlablah** [comment]
Discussion:
This sounds like a request that failing updates are rolled back to their previous state. 
But since we don't touch the local folders until after we have successfully downloaded the update, and extracted the content of the archive to a temporary location, this is about handling errors after this point.
Perhaps we could rename the current folders instead of replacing them, and keep them around until after the update finishes?

Also:
I just did a quick test to see if we have issues updating ElvUI specifically. 

To do that I downloaded the previous version of ElvUI by editing the current download URL on the tukui website
From: https://www.tukui.org/downloads/elvui-11.52.zip
To: https://www.tukui.org/downloads/elvui-11.51.zip
I then used Ajour to update it to version 11.52 which worked out.

@hamdeli When the update failed, did you notice if anything was left of the old version? Like a few files that it was unable to delete. Or was the ElvUI and ElvUI_OptionsUI folders both gone?

**Comment by hamdeli** [comment]
@mlablah ElvUI folder was gone, but ElvUI_OptionsUI was still there. I will also add that I am running app version 0.3.3.

**Comment by casperstorm** [comment]
> @mlablah ElvUI folder was gone, but ElvUI_OptionsUI was still there. I will also add that I am running app version 0.3.3.

0.3.3, which currently is on master is not 100% stable yet. Once 0.3.3 is stable, and it’s released then going forward master will always be latest stable release but for now it’s actually working as develop branch as well meaning it’s from time to time pretty unstable. 

More important though, does this issue happen on 0.3.2?

Thanks for the detailed report.

**Comment by hamdeli** [comment]
@casperstorm I tried this in 0.3.2, and was able to reproduce it, but when gathering screens with proper timestamps and logs in a followup test, the update actually succeeded. So it seems spotty... Id like to get some logging around this

Here are screens that you see when it errors out.
![error_2020-09-14_093758](https://user-images.githubusercontent.com/660665/93094847-6f29c580-f670-11ea-9d03-bf866a899541.png)

ElvUI folder is removed from list:
![29_addons_ 2020-09-14_093905](https://user-images.githubusercontent.com/660665/93094966-8bc5fd80-f670-11ea-9ff0-346e1fec0ab4.png)

ElvUI folder not present in addons:
![elvui_folder_deleted_2020-09-14_094316](https://user-images.githubusercontent.com/660665/93094968-8bc5fd80-f670-11ea-9c68-a353dfa6091a.png)


reset evlui back to 11.51 and retested it to get proper screens and it was actually a successful run:
![30_addons_updateElvUI_2020-09-14_094714](https://user-images.githubusercontent.com/660665/93095095-b1530700-f670-11ea-92a2-459e73a37a17.png)

Properly updated.
![succeeded_2020-09-14_095153](https://user-images.githubusercontent.com/660665/93095098-b1530700-f670-11ea-8692-d15623fc626b.png)

**Comment by casperstorm** [comment]
Thanks for the detailed log, and screenshots.
I think we have everything needed to solve this issue. I'll try to expedite this right after I am done working on #108.

**Comment by casperstorm** [comment]
This became relevant again when Tukui API was down.

**Comment by N6REJ** [comment]
probably need a try/catch after all i said and done to be sure nothing went awry.
