### ISSUE TITLE
in macOS, Menu bar has no options.

### ISSUE THREAD

**Issue by dblanch369** [casperstorm/ajour#143]
**Describe the bug**
Normally, a macOS application has a "Quit" function, if nothing else, on the menu bar drop down.  I don't see any drop-downs at all.

**To Reproduce**
1. Go to 'Ajour' on Menu bar
2. Click on 'Ajour'
3. Scroll down to ....  Can't, nothing appears

**Expected behavior**
Expect to see a dropdown menu, with at least one option, to "quit" the application.  An "About" would be nice as well ;)

**Screenshots**

**Software involved**
Please complete the following information:
 - OS: macOS 10.15.6
 - Ajour version: 0.3.4
 - (if applicable) Addon name, flavor (classic or retail) and version:  n/a
[ajour.log](https://github.com/casperstorm/ajour/files/5300173/ajour.log)
[ajour.log](https://github.com/casperstorm/ajour/files/5300192/ajour.log)

**Additional context**
It also doesn't see anything other than retail, and classic.  beta and ptr are not detected.  Not sure if related or not, or if it's just not set up yet.

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.

**Comment by casperstorm** [comment]
This is a upstream problem, related to winit.
I've had a PR (https://github.com/rust-windowing/winit/pull/1583) lying since may to add menu items. I'll see if we can call the api's directly to add this behaviour but otherwise we have to wait for upstream.

I'll close this now, but keep an eye out if my PR gets merged.
