### ISSUE TITLE
AddonSkins (retail) detected as being AddonSkins Classic

### ISSUE THREAD

**Issue by AltBridge** [casperstorm/ajour#145]
**Describe the bug**
AddonSkins is being detected as being AddonSkins Classic. Doesn't matter if it's installed from Curseforge or Tukui.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.3.4
 - AddonSkins (retail) 4.44

**Comment by casperstorm** [comment]
So I am just posting my findings here.
When we send the fingerprint from https://www.curseforge.com/wow/addons/addonskins to curse we an id that matches https://www.curseforge.com/wow/addons/addonskins-classic. This is clearly a bug from Curse, but i'll look into if we can do anything about it.

**Comment by mlablah** [comment]
Adding my own observation as well. It looks like the authors have actually uploaded the retail version of the addon both places. So curseforge isn't wrong per se. addonskins 4.42 and 4.43 is present both places.

**Comment by casperstorm** [comment]
I had a look at this again. This is a mistake by the addon creator. Let me take you through what happens:

1. We fingerprint the `AddonSkins`.
2. We ask CurseForge for information regarding the fingerprint. 
They send back (essentially) two pieces of information we use to populate a addon in Ajour:

* Data regarding the **CURRENT** local version.
```json
	"id": 325109,
	"file": {
	    "id": 3003505,
	    "displayName": "4.44",
	    "gameVersionFlavor": "wow_classic"
        }
```
    
* Data regarding the **LATEST** remote version.


```json
	"id": 3003505,
	"displayName": "4.44",
	"fileName": "AddOnSkins-4.44.zip",
	"gameVersionFlavor": "wow_classic"
```

So here is where it goes wrong:

1. The `id: 325109` resolves to AddonSkins Classic: https://addons-ecs.forgesvc.net/api/v2/addon/325109
This is obviously an error because you would expect to get AddonSkins here.

2. The creator (i assume) has marked **ALL** versions only compatible with `wow_classic` as you can see in the `gameVersionFlavor`.

To me it sounds like that `1.` is a mistake by CurseForge, and `2.` is the creator who made a mistake.
