### ISSUE TITLE
Not detecting CT_MOD mods

### ISSUE THREAD

**Issue by Ufleku** [casperstorm/ajour#158]
**Describe the bug**
In the list of installed addons the CT_MOD ones are not detected and listed

**To Reproduce**
Install ajour
Select the warcraft folder
Scan for addon

**Expected behavior**
CT_MOD addons in the list to be updated

**Screenshots**
![Ajour_Bug](https://user-images.githubusercontent.com/72122977/94649981-1a37b180-02f6-11eb-87aa-fed2659944c9.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 ver. 1909
 - Ajour version: ver. 0.3.4
 - (if applicable) Addon name, flavor (classic or retail) and version:
CT_Buffmode
CT_Library
CT_Core
CT_Partybuff
updated version for Retail on Curseforge 3 days ago
**Additional context**
n/a

**Log Output**

[ajour.log](https://github.com/casperstorm/ajour/files/5303499/ajour.log)

**Note**
Checking the log, it looks like the app detected them, but it's not clear why they weren't listed: could it be because only some of the whole CT_MOD package were installed?

**Comment by casperstorm** [comment]
Thank you for reporting this bug, @Ufleku.
So the issue is a little technical, but essential Ajour does not support if you modify and/or remove any folders. Ajour generates a hash, which is used for matching and since you removed some folders this hash is not valid.

I would suggest you re-add all the CTMod folders (or just reinstall the addon) and then disable what you don't need inside wow it self. This should solve your issue:

<img width="888" alt="Screenshot 2020-09-30 at 10 49 37" src="https://user-images.githubusercontent.com/2248455/94664629-680ae480-030b-11eb-9653-e3ed28646708.png">

**Comment by Ufleku** [comment]
Hi, 
I did as suggested: reinstalled the whole CT_MOD addon and then restarted Ajour forcing
 a refresh : first i simply clicked on the refresh button (no change), then i forced, in setting, the scans of the addon forlder (still no effect)
![Ajour_Bug2](https://user-images.githubusercontent.com/72122977/94671411-22064e80-0314-11eb-979d-d8cc5c087b58.png)
I'm adding also updated ajour.log
[ajour.log](https://github.com/casperstorm/ajour/files/5304639/ajour.log)

**Comment by casperstorm** [comment]
Can you try to remove `fingerprints.yml` from you Ajour folder and then restart Ajour again?

**Comment by Ufleku** [comment]
Now it works fine
Thanks a lot
