### ISSUE TITLE
Suggestion: plugin architecture

### ISSUE THREAD

**Issue by wkrueger** [casperstorm/ajour#175]
Just a (quite hard to implement) idea...

Today we open wow
Then we open raider.io electron app
Then we open twitch electron app
Then we open wago electron app
Then we open warcraftlogs electron app
(At least TSM is not an electron app)

How could we open less apps and yet keep the development distributed?
Yeah, I mean, its hard... just leaving the idea here.

**Comment by casperstorm** [comment]
I think this is an intersting topic to discuss. It does relate to other places as well. Mobile applications serves to do one single purpose rather than multiple. Remember when Facebook had Messenger incorporated? Everyone was yelling when they made the split. Now that is forgotten. We open up the weather app when we need to look at the weather, we close it when we are done. 
I see this ecosystem the same way. You open Ajour when you want to manage your addons, you close it when you are done. You open Warcraftlogs when you are about to raid, you close it when you are done. Etc.

We need to move away from big bloated applications like Twitch. This is the way. The real problem with the list you posted is everyone doing electron apps which leaves such a big memory footprint you can't have many applications open. Thats a problem.

I'll close this 'issue' but feel free to keep keep posting in it.
