### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by teqnodude** [casperstorm/ajour#182]
It would be helpful if the app could be made portable where it allow to store it's settings in it's own folder instead of %APPDATA%\ajour. A suggestion would be to code it to either run the ajour file with a flag ie `ajour.exe -p` or simply that it looks for a file called `ajour.portable` in program dir that makes it portable. I'm sure I'm not the only one that would prefer to have it this way.

**Comment by casperstorm** [comment]
Thank you for the suggestion, @teqnodude. Great idea.
For now, however, this is not in scope, but I have added it to our `inbox` in the [Roadmap](https://github.com/casperstorm/ajour/projects/2#card-46591946). 
This way it might be picked up by someone who want to help contribute to the project. It's a great initial task.

I'll close this for now since it has beed added to Inbox.
