### ISSUE TITLE
Make settled release channel also download upper release versions

### ISSUE THREAD

**Issue by Ruffz** [casperstorm/ajour#186]
_**Is your feature request related to a problem? Please describe.**_

Actual release channel setting only check if selected release is available.

_**Describe the solution you'd like**_

This setting should be the "minimum stability release you want to download" 
- Alpha should also check and download "Beta" & "Release" version
- Beta should also download "Release" version

**Comment by casperstorm** [comment]
Hi @Ruffz,
The current logic functions like that. So if you consider the following example:
```
Stable: 1.0
Beta:   1.1
Alpha   0.9
```

If you select `Stable` and press `update` you will get `1.0`.
If you select `Beta` and press `update` you will get `1.1`.
If you select `Alpha` and press `update` you will get `1.1`

Notice that `Alpha` jump one up and grabs `Beta` because `Alpha` is older than `Beta`.

**Comment by Ruffz** [comment]
Your example is exactly what I ask, but not what I've seen.

An addon (Masque:Apathy) showed no update when set to Alpha but showed one update when set to Stable.

I will check log and report if it happen again.
