### ISSUE TITLE
Binary Signing

### ISSUE THREAD

**Issue by ianmarmour** [casperstorm/ajour#193]
**Is your feature request related to a problem? Please describe.**
Users see exe as a dangerous file in their browser.

**Describe the solution you'd like**
Take donations (if you're not already) and sign the exe's :)

**Describe alternatives you've considered**
Leave it as is, users still have a warning.

**Additional context**
Really not a massive issue but it would be nice leading up to the main release.

**Comment by LEGOL2** [comment]
I did a small research on software signing and I think it's crazy. The cheapest I found is 250$ for a year! The thing about windows is that if enough people use `ajour.exe`, then this message about unknown file will disappear.

**Comment by casperstorm** [comment]
> I did a small research on software signing and I think it's crazy. The cheapest I found is 250$ for a year! The thing about windows is that if enough people use `ajour.exe`, then this message about unknown file will disappear.

I really hate this gatekeeping. Ajour is an excellent example where the code is open source and has a growing community. Why don't they have a plan for signing open source projects like this? Exactly like [Let's Encrypt](https://letsencrypt.org/). As it is right now I don't want to collect donation for supporting such a model.

This decision will costs users because Windows Defender is going nuts but I dont see a solution in the near future for this.
