### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by ianmarmour** [casperstorm/ajour#195]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
A simple installer for each supported platform.

**Describe alternatives you've considered**
N/A

**Additional context**
It would be nice to have Ajour installed on my system without having to go set that up manually, this isn't major but just more nice user experience stuff.

**Comment by LEGOL2** [comment]
Ajour on windows is a single `.exe` file, which means there is nothing to install. Download file, place whenever you wish and run it. Installers are used to setup dependencies and resources but ajour is standalone program.

**Comment by casperstorm** [comment]
I agree with @LEGOL2 on this.
Since we are able to ship this as a single executable the only reason to have a installer is to generate shortcuts to various locations. One of our core values in Ajour is to keep the simplicity down thus I don't think we should focus on adding an installer for that sole purpose.
