### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#2]
As a User I want to be able to launch the app. 

When the app is launched it should display a GUI with a list of currently installed addons, their version and the latest version available online.

Pseudo code:
* Display GUI. 
  * `Update All`, `Refresh`, `Settings` buttons.
  * Scrollable list.
* Execute `Refresh`.

**Comment by casperstorm** [comment]
- [X] Display GUI
- [X] Update All
- [X] Refresh
- [ ] Settings
- [X] Scrollable list
- [X] Execute Refresh

It is now possible to load the app, and view the parsed addon in a scrollable list. Two buttons are present in the controls-row: Refresh and Update All. Refresh and Update All logic is not fully implemented (this will happen in #4 and #3).

Settings for for version 1.0 will be in a `yml` file the user has to edit themself. Later, this file will be parsed and shown in the GUI for easier accessibility. 

This issue is considered closed for now.
