### ISSUE TITLE
[Question] What do you think about the overwolf statement?

### ISSUE THREAD

**Issue by Neurotoxin001** [casperstorm/ajour#225]
https://medium.com/overwolf/our-stance-on-scraping-curseforge-19f4559a322a

**Comment by casperstorm** [comment]
Ajour does not use scraping to gather data from CurseForge (or TukUI for that matter). We use public API's that don't use any system for authorization. Everyone can request data from these API's. This also means that CurseForge easily can track engagement, e.g. increment a download count, when someone downloads an addon through Ajour.

Ajour does not re-host, or redistribute addons and our impact on the earnings of addon authors is no different than someone using an adblocker when visiting their website. We would love to be able to include a donation link next to the description of every addon so that the authors (and CurseForge!) can be rewarded for their work. But currently this information is not exposed in the API, and since we don't do any scraping of their website, we cannot retrieve it.

Overwolf has not contacted me, but should they decide to add authorization to their API's, this will of cause limit the functionality of Ajour. However we have begun the ground work for an open source alternative.

**Comment by casperstorm** [comment]
I had a conversation with Overwolf today to discuss their concerns and the future of Ajour (and similar third party addon managers).

Their primary concern is that people who use their API outside of their official app and website cost them money. They are stuck with the cost of hosting thousands of addons, for millions of users. Without the revenue from ads and user activity tracking, they don’t have anything to share with creators who upload their addons to their platform. 
My belief is that having an open and accessible API does come at a cost but it also tells you a lot about a company. It invites developers to create something awesome which in turn makes their platform the obvious choice for creators.

We at Ajour want to see CurseForge remain relevant and creators get rewarded for their work. But ultimately, we see addons and their distribution as a kind of volunteer work (not just because of Blizzard’s policy on addons, but that is part of the reason).

Therefore, we would prefer a solution that makes it super easy for users who are happy with the addons they use, to show their support by donating to creators and their partners. This could take the form of a donation button in the UI of third party addon managers, sending users to CurseForge should they want to donate. But this information is currently not available in the CurseForge API.

For now, Overwolf have confirmed that the API’s will remain open.
