### ISSUE TITLE
Sometimes showing not all addons

### ISSUE THREAD

**Issue by Neurotoxin001** [casperstorm/ajour#254]
**Describe the bug**
Sometimes after startup it's showing not all addons so I must click "refresh"

**To Reproduce**
1. Run ajour
2. If not all addons loaded click "refresh"

**Screenshots**
https://i.imgur.com/WD5to0J.mp4 - it's always different number of "loaded addons"

**Software involved**
 - OS: Windows 10 LTSC 1809
 - Ajour version: 0.4.1

**Log Output**
[ajour.log](https://github.com/casperstorm/ajour/files/5391276/ajour.log)

**Comment by Xorag** [comment]
I've seen this exact same behavior in the Twitch client since Shadowlands released, I just switched to Ajour to try and rectify it as the twitch client was showing me as having old versions installed, failing to scan all addons all of a sudden, so maybe suspect something wonky going on with twitch/curse? Just my 2 cents.

**Comment by Ruffz** [comment]
See #249  & #251

**Comment by casperstorm** [comment]
#239 – it is because APIs is not giving us correct data after they have been slammed ever since pre-patch hit.
We have to wait it out.
