### ISSUE TITLE
Don't attempt to write into symlinked Addons!

### ISSUE THREAD

**Issue by Yakehira** [casperstorm/ajour#255]
**Describe the bug**
When you symlink an addon into the addons Folder and download an addon with the same name (i tested my own Addon), it will write into the symlink folder and replace the files at the source which is really bad if you are a developer who doesn't use source control to recover your files :P

**Expected behavior**
Delete the link and write a new folder (after warn, because it really should let you know it's getting rid of your link) so it can never write into the link source even by misclicking.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 0.4.1

**Comment by tarkah** [comment]
@Yakehira thanks for opening the issue! We had some logic previously in place to remove the destination folders before extracting an addon. However, there appeared to be some gaps in that logic. #261 should fix that. It'd be great if you know how to build from source so you can test that PR prior to us merging, but I feel pretty confident it'll resolve your issue here.

**Comment by tarkah** [comment]
I tested by creating a symlink matching the folder name of an Addon (I used Recount) with some files behind the symlink. I downloaded Recount from the Catalog. Previously it overwrote my files. With the PR, it successfully deleted the symlink, created a new folder and extracted the addon, preserving my files.
