### ISSUE TITLE
Ajour not showing installed addons

### ISSUE THREAD

**Issue by xucaen** [casperstorm/ajour#264]
I noticed some addons I have installed are not being updated by ajour.  I'm not sure if this is a bug or why they are not showing up.

![image](https://user-images.githubusercontent.com/17462261/96368078-c1528080-111f-11eb-954c-904bc59440a9.png)

**Comment by Together34** [comment]
I've a similar/same Issue - Although it seems refreshing sometimes helps populate/depopulate the list 
![image](https://user-images.githubusercontent.com/58236114/96368579-1fea1f80-115d-11eb-8773-1752b8a0ef69.png)
![image](https://user-images.githubusercontent.com/58236114/96368583-2b3d4b00-115d-11eb-9643-6dcc12eb8e50.png)
![image](https://user-images.githubusercontent.com/58236114/96368595-3db78480-115d-11eb-8111-3705b2bc31f9.png)
![image](https://user-images.githubusercontent.com/58236114/96368618-60e23400-115d-11eb-879f-361e35d5c46f.png)
Twitch pic for "addon list for extra context" 
![image](https://user-images.githubusercontent.com/58236114/96368633-82432000-115d-11eb-84a6-c01ed4104af8.png)

//Thank you for the good work, loving the sleek minimalism.

**Comment by casperstorm** [comment]
This is unfortunately a issue because the CurseForge api returns garbage right now (see #239).

Short shorty:
You ask the API two questions they answer two other questions. Then you ask the API the same two questions, this time it answer one of them. Rinse repeat. This is why you can press refresh and see different results from time to time. It is likely due to their caching server failing.

TL;DR: We have to wait until CurseForge fixes their api.
