### ISSUE TITLE
Ajour does not remember window location/sizing between launches

### ISSUE THREAD

**Issue by Xorag** [casperstorm/ajour#269]
Running 0.4.1 on Windows 10 20H1 I've noticed that if I open Ajour and full screen it, closing it and reopening it you will observe it doesn't reopen to a full screen/maximized state - it always opens windowed.

Also between launches it also goes to a default anchor point similar to a windows command prompt, so if I've moved it to a specific location on my monitor it will reopen to the default anchor point.

So my request would be to simply have the app remember where it's been moved, and whether it was fullscreen or windowed.

Thanks! :)

**Comment by braddyb7** [comment]
A couple of things to add here from my own experience. 

Ajour always seems to open at the same anchor point (I'm guessing ~50x50 pixels from the top left of the screen but maybe a bit more). I've had no issues with Ajour remembering its window size, also running version 0.4.1 on Windows 10 2004. These both, however, cause some odd behaviour if it is closed and reopened from either Maximized or Minimized states.

When closed while maximized, it will remember the window size and be partially off the edge of the screen when it is reopened as the top left corner of the window is always anchored to the same point on the screen when opened. So the right and bottom ~50 pixels of the window are off the edge of the screen.

When closed while minimized (e.g. right click the icon on the task bar and close window), it seems to remember its window size as 0px x 0px. The Ajour icon ends up on top of the minimize button and there is no actual window content other than the standard min, max, and close buttons, as shown by the image below of the whole Ajour window:

![image](https://user-images.githubusercontent.com/439144/96621310-62982d00-1300-11eb-8dd1-3b5fcb3ce752.png)

**Comment by Ruffz** [comment]
#99 :D

**Comment by tarkah** [comment]
This is mostly an upstream issue, we cannot get access to window position or set initial window position with the library we use. Even further, we can't tell when a resize is due to a Maximize / Restore, we just see a resize occurs and what the new height / width are. Until we are given better access to the underlying windowing library through `Iced`, we are kind of stuck here. Seems like `Iced` is waiting on an upstream issue for them to put in place.

Relevant upstream issues:

https://github.com/hecrj/iced/issues/515
https://github.com/hecrj/iced/issues/556

**Comment by Xorag** [comment]
As an update I found this workaround/solution with using a Windows shortcut to force the window to be maximized on launch - https://www.tenforums.com/tutorials/93142-always-open-shortcut-normal-minimized-maximized-windows-10-a.html
