### ISSUE TITLE
Open Ajour on startup

### ISSUE THREAD

**Issue by Plougz** [casperstorm/ajour#288]
A simple checkbox to open the program on startup :)

**Comment by casperstorm** [comment]
For now I would recommend you follow: [Add an app to run automatically at startup in Windows 10](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd.).
In the future we might add support directly in the app, but for now I feel like it is up to the user since it is natively supported by the OS. 

Thanks for reporting, Plougz.
