### ISSUE TITLE
API does not always return gameVersion for some addons

### ISSUE THREAD

**Issue by 2case** [casperstorm/ajour#336]
**Describe the bug**
When a TOC file of an addon have empty lines in it (ex. LiteBag, MogIt, Postal or AllTheThings) the game version is missing.

**Expected behavior**
Ajour should show the game version as on all other addons

**Software involved**
 - OS: Windows 10
 - Ajour version: 0.5.0
 - Example Addons: LiteBag, MogIt, Postal, AllTheThings

**Comment by casperstorm** [comment]
The problem here is not empty lines in TOC files, but the API not returning the `gameVersion` for those specific addons.
This can be caused by two reasons:

* The author didn't specific it.
* The API does not properly return it.

In this case it's the latter, so i'll take a look at why it didn't return it properly. We could however consider a fallback option to the TOC file, if it has a `## Interface: *` field.

**Comment by casperstorm** [comment]
This is fixed, will be coming out in `0.5.1` 👍🏻

**Comment by 2case** [comment]
I have still two addons which have no game version with ajour v0.5.1:

- LiteBag (9.0.10/Stable)
- Postal (v3.65/Stable)

Not really a mess, just for info :-) 

Bye,
Tom.
