### ISSUE TITLE
Repetitive if not invalid naming

### ISSUE THREAD

**Issue by azder** [casperstorm/ajour#359]
Top of the window contains tabs for switching named `Retail`, `Retail PTR`, `Retail Beta`, `Classic`.  The overly repetetive word just makes it more confusing.

Sidstepping the issue there isn't a game named _Retail_, only _World of Warcraft_. One only needs to see the Battle.Net launcher options above the big Play button 
![battle-net-launcher-options-01](https://user-images.githubusercontent.com/61147/99294781-d0267300-2844-11eb-8cfe-956e864dc5ce.PNG).

One might go with the offical names (or abbreviations like WoW, WoW PTR, Beta, PTR Classic) or with just the directory names which are unambiguous and brief
![explorer-wow-directories-01](https://user-images.githubusercontent.com/61147/99295258-7d998680-2845-11eb-8125-f041706a3773.PNG)

**Comment by casperstorm** [comment]
For now we will stick with the current naming convention.

Thanks for reporting.

**Comment by azder** [comment]
> For now we will stick with the current naming convention.

No rationale provided.

**Comment by tarkah** [comment]
@azder no doubt people know that this app is for _World of Warcraft_ / WoW, so this would be redundant. We landed on Retail vs Classic because that's what Blizzard themselves named things at the folder level (`_retail_` vs `_classic_`) and what pretty much the entire internet uses to distinguish between the two. The only thing it's repetitive for is PTR and Beta, but there is PTR for both flavors of the game, so we need differentiate.

**Comment by azder** [comment]
We landed on Retail vs Classic because that's what Blizzard themselves named things at the folder level (_retail_ vs _classic_) 

Yet, there isn't _retail beta_ named directory. While the word _retail_ it self is not accurate, I did also point out you can use the actual directory names which are unambiguous and non-repetitive.
