### ISSUE TITLE
Install Addon From Arbitrary Git Repository

### ISSUE THREAD

**Issue by Flat** [casperstorm/ajour#391]
**Is your feature request related to a problem? Please describe.**
You are currently only able to install addons from GitHub or GitLab  that have releases.

**Describe the solution you'd like**
The ability to to download any git repository and install it as an addon. This can be as simple as a git clone for example ElvUI.
wowa has this ability already, and although it is not a GUI works well. As WoW addons are lua and do not need to be compiled or really even packaged for a release a simple clone of the repository should be fine, taking into account that all folders in the repository may or may not be the top level addon folders.

**Comment by tarkah** [comment]
Thanks for the suggestion! As you point out, we can't guarantee how a repository is laid out and if the addon is in the root, or a subfolder. Due to this, we decided to only initially support repos that publish releases with a clean zip asset we can unpack. This obviously limits us to using the APIs and why we currently only support GitHub and gitlab.

That's not to say it'd be impossible to attempt to parse the source, but it definitely adds some complexity, on top of needing to bundle some git dependencies into Ajour so we could do the clone.  

I'm curious how wowa handles these considerations, so I'll definitely check that manager out.

**Comment by Flat** [comment]
The git support in wowa is fairly basic and assumes the repository is the top level of interface. You can see the code that handles it here https://github.com/antiwinter/wowa/blob/master/source/git.js pending free time I may take a stab at this myself, although I have admittedly, not had time to look at the ajour codebase as of yet. Tracking git hashes for updates and a switch for assume interface level or need to clone into a subdirectory would be the basics for this feature I would think. Most of my exposure with open souce WoW addons is tukui/elvui and they are almost all formatted into assuming the directories in the repositories contain the folders for the addons.

Additionally yes more dependencies would likely be required to clone the repositories without requiring the user to install git. [git2](https://docs.rs/git2/0.13.12/git2/) looks like it would be an uncomplicated crate for git functionality, with minimal dependencies.
