### ISSUE TITLE
Feature Request: Add Local Folder Navigation

### ISSUE THREAD

**Issue by whoiskevinrich** [casperstorm/ajour#395]
**Is your feature request related to a problem? Please describe.**
Sometimes users wish to modify the local version of a mod.

**Describe the solution you'd like**
Add a link to the local folder for the mod (see screenshot)

![image](https://user-images.githubusercontent.com/2496620/100520664-c3165780-3153-11eb-8ac9-1f865c5180fc.png)

**Comment by casperstorm** [comment]
A little unsure how this should work. A addon is often bundled together with multiple folders. As an example:

```
AtlasLoot
AtlasLoot_BattleForAzeroth
AtlasLoot_BurningCrusade
AtlasLoot_Cataclysm
AtlasLoot_Classic
AtlasLoot_Collections
AtlasLoot_Crafting
AtlasLoot_Factions
AtlasLoot_Legion
AtlasLoot_*.*
```

What would you expect happen in this case? What would open?

**Comment by whoiskevinrich** [comment]
That's a good question. I hadn't noticed that before. I'm not familiar enough with rust to see where you enumerate the addons from the addon directory, but I had assumed it was through the TOC file.

**Comment by tarkah** [comment]
Correct, we parse everything from the top-level TOC file, but there is still a many-to-one relationship between folders and an "add-on". I'd be hesitant to add this as well because our add-on matching can break against curseforge API if users make local modifications to the add-on. So not sure it's something we should actively make more accessible :P
