### ISSUE TITLE
Ajour not finding retail addons

### ISSUE THREAD

**Issue by ExiledProdigy** [casperstorm/ajour#412]
**Describe the bug**
Giving error showing "Whoops, you have no retail addons!" which I have over 30 installed. Verified directory folder and reinstalled version 0.5.3. Issue remains. 

**To Reproduce**
1. Start Ajour

**Expected behavior**
Full list of currently installed addons

**Screenshots**
![image](https://user-images.githubusercontent.com/75466101/101125781-ab115e80-35bf-11eb-9b08-bd6a6ee30141.png)
![image](https://user-images.githubusercontent.com/75466101/101125822-bebcc500-35bf-11eb-852d-50a4bc264ee8.png)

**Software involved**
Please complete the following information:
 - OS: Windows 10 Pro 64 bit
 - Ajour version: 0.5.3
 - (if applicable) Addon name, flavor (classic or retail) and version: 

**Additional context**
N/A

**Log Output**
Paste the content of `ajour.log` from `%APPDATA%\ajour\ajour.log` on Windows or `$HOME/.config/ajour/ajour.log` on Mac/Linux.
[ajour.log](https://github.com/casperstorm/ajour/files/5640769/ajour.log)

**Comment by usrbinpikachu** [comment]
Getting the same thing. The likely cause seems to be this 502:

`21:47:30.541 [ajour_core::parse][DEBUG] Retail - 110 addon folders successfully parsed from '.toc'
21:47:30.541 [ajour_core::parse][DEBUG] Retail - 4 cached entries
21:47:30.541 [ajour_core::parse][DEBUG] Retail - 105 unique fingerprints to check against curse api
21:47:32.335 [ajour::gui::update][DEBUG] Interaction::ModeSelected(About)
21:47:33.723 [ajour::gui::update][DEBUG] Interaction::OpenLink(https://getajour.com)
21:47:41.969 [ajour][ERROR] Failed to parse addons
21:47:41.969 [ajour][ERROR] caused by: Invalid status code 502 Bad Gateway for url https://hub.wowup.io/curseforge/addons/fingerprint`

wowup.io is returning 'message	"Missing Authentication Token"'

**Comment by casperstorm** [comment]
Sorry for this. Api was down, but should be up now.
