### ISSUE TITLE
[RC] Selecting an item from a pick_list which expands over a table_row.rs will fire `on_press` event

### ISSUE THREAD

**Issue by casperstorm** [casperstorm/ajour#416]
**Describe the bug**
When you select an item from a `pick_list` inside the Catalog it will fire `on_press` on the cell below the `pick_list`.
This is only happning after https://github.com/casperstorm/ajour/commit/b5ab26f4875b19fb725e7324f98fd7f6f504aefa. Not in production yet.

**To Reproduce**
1. Go to Catalog
2. Press eg. All Catagories
3. Select a category
4. Notice the addon underneath that catagory you pressed will open up in your browser.

What happens is that the press apparently goes through the `pick_list` and the `table_row` gets it, and then calls `on_press` for the addon. The relevant code is here.

https://github.com/casperstorm/ajour/blob/2a4d2f3d069fe2781fdd0953614b2bed97b5ffda/crates/widgets/src/widget/table_row.rs#L220-L222

@kawashita86 or @tarkah – is this something you can take a stab at?

**Comment by kawashita86** [comment]
@casperstorm I've performed a bit of investigation to understand why the click is captured by both the pick_list and the table_row.
While we check for `Event::Mouse(mouse::Event::ButtonReleased(mouse::Button::Left))` on `table_row`, the `pick_list` checks for `Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left))`, thus the event `ButtonReleased` when an option is selected is not captured by the overlay menu but gets back to the table_row as ignored and gets captured by the widget since it's "free". 
Seems that an easy fix could be changing the `ButtonReleased` event to `ButtonPressed` on the table_row `on_event`:
```
                if let Event::Mouse(mouse::Event::ButtonPressed(mouse::Button::Left)) = event {
                    if let Some(on_press) = &self.on_press {
```
