### ISSUE TITLE
Backup Addons at Interface level instead of Addons folder only

### ISSUE THREAD

**Issue by d3ntatous** [casperstorm/ajour#433]
**Is your feature request related to a problem? Please describe.**
Some addon packs and I use the Interface folder for custom textures rather than the AddOns one. 

**Describe the solution you'd like**
I would really like is for the backup feature to not only backup the addons folder, but the parent one instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by mlablah** [comment]
@d3ntatous Thank you for filing this feature request. I took the liberty of editing the issue title and description.

You mention that certain addons use the Interface folder to store custom textures (rather than their specific addon folder). Could  you mention some examples where that is the case? The reason i ask is to gauge how common this practice is, and also because Ajour would not be able to install or update addons that wants assets stored outside the Addons folder.

**Comment by d3ntatous** [comment]
Hm, you are right, the update issue is a blocker, I was mainly thinking it from the backup feature perspective, rather than the update one. On your question, a rather recent UI that uses custom textures is AbyssUI. Would it be possible to ask for a checkbox that allows to include the total of the interface folder during backup?

**Comment by tarkah** [comment]
I don't see any issue with including everything in `Interface\**` whereas right now we only include everything in `Interface\AddOns\**`. 99% of people won't have anything to backup in that folder so it doesn't change anything. But at least for you, it picks up those files.

**Comment by tarkah** [comment]
@d3ntatous I've merged this change and it'll be available starting with 0.6.1-rc.1 which we're releasing today

**Comment by d3ntatous** [comment]
Thanks, and have a nice holiday!!

**Comment by tarkah** [comment]
You too!
