### ISSUE TITLE
Local Cache of the Addon Catalog

### ISSUE THREAD

**Issue by msvi** [casperstorm/ajour#435]
**Is your feature request related to a problem? Please describe.**
Loading the addon catalog is very slow sometimes. Yesterday, I couldn't load the catalog even after 20 minutes of waiting. Today, I had to wait around 5 minutes before the catalog was showing. This seems to be a GitHub problem, as I often experience very slow downloads (just a few kb/sec) when downloading releases from GitHub.

**Describe the solution you'd like**
The addon catalog should be cached locally and only be downloaded when the user requests it. Ajour should show the time of the last refresh. During the download, it would be useful to show the progress and speed, and provide an option to cancel.

**Describe alternatives you've considered**
For me, downloading e.g. the wowi.json directly from the current source code is almost instant, while the download from the "releases" page is very slow. It might help to simply download from the master branch instead of using the GitHub releases.

Another solution would be to host the catalog somewhere else. But I think this might be too much effort and it might not improve the situation for all users.

**Additional context**
I'm located in Germany. After doing a quick search, I found other people reporting problems with release downloads from GitHub outside the US. Usually I experience the slow dowloads during the day. When I'm using Ajour very late in the evening the catalog is showing immediately. Ajour shows updates to already installed addons immediately and updating them also works fine.

**Comment by mlablah** [comment]
@msvi Thank you for the suggestion. We have on our internal backlog an item to add catalog caching, so that it isn't downloaded whenever the user launches Ajour, but only when necessary and then reuse that data until it's deprecated. 

Providing some kind of progress information while the download is happening is a good idea, but I'm not sure if it's possible with our current implementation. It will be worth investigating. :)
