### ISSUE TITLE
Documentation for addon developers on release channels through GitHub

### ISSUE THREAD

**Issue by zeeraw** [casperstorm/ajour#438]
**Is your feature request related to a problem? Please describe.**
When using GitHub for provisioning an addon for my guildies, I want to make use of the alpha, beta, and stable release channels. Do they in some way map to release status of GitHub releases and if so how?

**Describe the solution you'd like**
A page on the repository Wiki describing how release channels work.

**Describe alternatives you've considered**
Releasing through an addon repository like Curse or WoWInterface. But I'd rather keep an in-house addon like mine through GitHub.

**Comment by mlablah** [comment]
@zeeraw Ajour currently only supports release channels for addons that are updated via CurseForge. Or put another way, the release channel feature was implemented to support the different channels offered by CurseForge.

For this reason addons from other sources are always considered "Stable" and setting the channel to anything but stable will have no effect.

For GitHub in particular, Ajour will look for the latest published release, not counting releases marked as "pre-release".

Perhaps we should consider mapping pre-release releases to the beta channel, so that users specifying beta (or alpha) will get those if present and newer than the regular release.

**Comment by zeeraw** [comment]
I see, thank you for the clarification, much appreciated.

It would be cool to make use of GH release states for the beta channel.

**Comment by tarkah** [comment]
I think it's fair to assume that `pre-release` maps to our `Beta` release channel. I'll assign myself to this and look at implementing it. Do you mind linking your addon? I'd love to test against it if you publish "Stable" as normal releases and "Beta" as `pre-release`?

**Comment by tarkah** [comment]
To clarify, I don't see us supporting `Alpha` vs `Beta` via Github / Gitlab since there is no standard built into either platform we can use to distinguish them. We can use the `pre-release` flag to at least distinguish between "Stable" and not stable. I think that should just map to our "Beta" so that if the user sets it as either Beta or Alpha in Ajour, they will get that `pre-release` to show as available.

We don't plan on implementing any proprietary metadata to distinguish things.

**Comment by tarkah** [comment]
I'd suggest adding some logic to your https://github.com/zeeraw/loot/blob/master/.github/workflows/releases.yml actions file that marks it as "pre-release" if alpha / beta are in the tag

**Comment by zeeraw** [comment]
@tarkah Yeah, that's what I intended to do in my workflow. Mark it as pre-release when my tags contain some keyword(s).

**Comment by zeeraw** [comment]
> To clarify, I don't see us supporting `Alpha` vs `Beta` via Github / Gitlab since there is no standard built into either platform we can use to distinguish them. We can use the `pre-release` flag to at least distinguish between "Stable" and not stable. I think that should just map to our "Beta" so that if the user sets it as either Beta or Alpha in Ajour, they will get that `pre-release` to show as available.
> 
> We don't plan on implementing any proprietary metadata to distinguish things.

I think that's wise to not add anything proprietary and use the facilities that already exists. So to clarify, what you're suggesting is that GitHub pre-release = Ajour Alpha & Beta?

**Comment by tarkah** [comment]
Yeah, it'll equal Ajour Beta, but if you set it to Alpha, it'll also pick up Beta releases (since Alpha is more bleeding edge). Sweet! I'll look into this over the next week.

**Comment by tarkah** [comment]
@zeeraw I've added support for "pre-release" releases from GitHub with #447. You can test that branch or wait for our next Ajour beta rerelease to try it out. I've tested with your repo and it works great!

One thing I noticed is your latest alpha release https://github.com/zeeraw/loot/releases/tag/v9.0.2-alpha.14 has the TOC version still set as `v9.0.2-alpha.12`. This causes Ajour to think it's .12 even when it downloads .14 and always think there is an update to fetch. Make sure to always update your TOC version to match your actual release tag so you don't run into this update loop issue.

**Comment by zeeraw** [comment]
Big thanks, this will help me and my guildies a lot.

**Comment by zeeraw** [comment]
> One thing I noticed is your latest alpha release https://github.com/zeeraw/loot/releases/tag/v9.0.2-alpha.14 has the TOC version still set as `v9.0.2-alpha.12`. This causes Ajour to think it's .12 even when it downloads .14 and always think there is an update to fetch. Make sure to always update your TOC version to match your actual release tag so you don't run into this update loop issue.

On this, I've noticed I'm just being lazy with updating the TOC. I'm trying to figure out a good workflow for making sure I can just interact with Git and not having to think about touching it in multiple places.

**Comment by tarkah** [comment]
Maybe you can create a simple script to bump the version in TOC file, add a commit, then tag it for that version as well?

**Comment by zeeraw** [comment]
Yeah, I’m considering what would be the most neat thing. Having it be authoritative from the git tag or from a script that upgrades the TOC, then tags.
