### ISSUE TITLE
Linux - Interface locked in small size

### ISSUE THREAD

**Issue by Pantar2205** [casperstorm/ajour#444]
**Describe the bug**
GUI window opens in a very small size. Not possible to resize or maximise.

**To Reproduce**
Open App on Linux

**Expected behavior**
open at normal size or be able to maximize/resize it.

**Screenshots**
https://imgur.com/a/C57YiZ4

**Software involved**
Please complete the following information:
 - OS: Ubuntu 20.10 Wayland
 - Ajour version: 0.5.4 to 0.6.0 (All releases after 0.5.3)

**Comment by casperstorm** [comment]
This is a duplicate of https://github.com/casperstorm/ajour/issues/427, so I am going to close it in favor for that.
To get you up to speed; I've fixed it in this PR: https://github.com/casperstorm/ajour/pull/440 but since I dont use Wayland I can't confirm it actually solves the issue.

Can you perhaps test it?

**Comment by Pantar2205** [comment]
I am sorry but I am ignorant and don't know how to test it. Is it straight forward enough to figure out? I have zero coding experience and my only  familiarity with github is to search and post for errors

**Comment by tarkah** [comment]
@Pantar2205 I'll upload an AppImage for you to test with shortly

**Comment by tarkah** [comment]
@Pantar2205 can you try this? It has the fix in it

[ajour-appimage.tar.gz](https://github.com/casperstorm/ajour/files/5725564/ajour-appimage.tar.gz)

**Comment by Pantar2205** [comment]
Can confirm this fixes all resizing issues
