### ISSUE TITLE
Better sorting of catalog search results

### ISSUE THREAD

**Issue by steven-fuller** [casperstorm/ajour#462]
**Is your feature request related to a problem? Please describe.**
When searching the catalog, changing the text in the search field resets the sort order to unsorted

**Describe the solution you'd like**
I would expect the selected column sorting to be applied to the search results and not the default order.

**Describe alternatives you've considered**
I can't think of any other than reapplying the sort order repeatedly when searching.

**Additional context**
Tested on Ajour 0.6.0 on Mac OS X 10.15.7 with the Curse catalog and the Tukui catalog.

To reproduce:
Search for "Deadly Boss Mods (DBM)"
Change the sort order to "Game Version" descending
Add a " " (space character) to the end of the search string
Notice that the column sorting is removed and a default order is applied.

More severe case:
Search for "Adibags"...

**Comment by tarkah** [comment]
Right now we use a fuzzy match with the query you input and sort on match score. If you add another character to the query, it resets the sort because we have a new match score for all add-ons to sort by. The problem is if we preserve a custom sort on column, there is no way in the gui to allow the user to resort based on match score (best match first, descending). So we either leave this as is, or we have to add an explicit column for match score

**Comment by KestrelWild** [comment]
+1 for some sort of change/fix to this. The other day I went to search for addons related to Kui Nameplates. There are a few of them, some not updated in years, so I went to sort by latest release, with Kui still typed in search box, and suddenly there are no Kui items in the list of results. I would expected to still see Kui addons, with the most recent at top.

**Comment by tarkah** [comment]
Even if you sort after querying, the results should still be "filtered" based on the query. Since you are seeing results that don't appear to be related at all (we fuzzy match the search term on both title and description), I think we need to increase the match score that we filter on.

I'll play around with this to see if I can find the score that only leaves in results with strong relevance.

**Comment by steven-fuller** [comment]
The point about sorting on match score is valid, and perhaps an additional column wouldn't be too onerous.

Fwiw, they might be completely unworkable or overly complicated, but here are some thoughts I have had about this:

The way I use catalog search, more recent results are generally more relevant to me than the current match scoring is using. Perhaps that could be used as factor in the scoring algorithm? For example, searching for 'adibags' and seeing a match for "Sorted", an Adibags alternative is more useful than seeing "Adibags_Legion" which was last updated 4 years ago. Download count might be also useful in scoring relevance, but tuning multiple weights seems tricky to me.

An option to force or disable fuzzy matching could be interesting (eg. '~Adibags' or '=Adibags') or even a specific column search might be useful to someone (eg. 'name=Details' or 'author=MysticalOS'), but at some risk of complexity. Compound searching would be great if the UI allows. (eg. 'description like auction and version >= 9.0').

I suppose a setting to only show catalog entries for game version >= x.x wouldn't be a horrible option.

**Comment by tarkah** [comment]
I think the additional weighting by "recency" is very valid. Another thought is to not even sort on fuzzy match score, and just leave in whatever column sort is already in place. So if you have things sorted on Latest Release, it keeps that when changing your search term. I'm hoping that if I tighten up the filter on fuzzy match score, all results will be relevant and therefore whatever way the user wants to sort things will return expected / valid entries.

So by default, things will be sorted by # Downloads, but the filtered results will at least all be valid against the search term (have something closely resembling the search term in the title / description).
