### ISSUE TITLE
Still on 0.5.3 because of this...

### ISSUE THREAD

**Issue by ZythDr** [casperstorm/ajour#474]
Please bring back the ability to view changelogs directly inside Ajour by clicking the remote version numbers as it used to work before version 0.5.4.

I don't understand why this was removed to begin with. I really liked this feature as it makes it a lot easier to keep up with changelogs rather than having to open up a browser tab for each addon, which in my case can be up to 10 tabs sometimes.

I really don't want to update Ajour until this feature gets re-implemented. 

Anyway, even if this doesn't get re-implemented into Ajour, thanks for this great addon manager!

**Comment by casperstorm** [comment]
I hear you loud and clear @ZythDr.
Honestly this kind of feedback is great because if no one yells when we make a wrong decision we would never know. We try to make the very best addon manager for the community, so obviously the community means a lot to us.

I made the decision to remove it, and the reason was that i wasn't happy with the implementation of it. And also because a lot of users couldn't understand why the formating was so random, and why some addons had to be viewed in the browser while others had the changelog directly in Ajour. I felt the consistency was off.

We are looking back into it.

**Comment by tarkah** [comment]
@ZythDr I've reimplemented this and merged into dev. This will be available as of 0.6.2-rc.1, which should be published here in the next day or so hopefully.

**Comment by ZythDr** [comment]
Oh wow, I half expected this to fall on deaf ears, or be ignored since you guys had felt the need to remove it before. It makes me very happy to see you've read, replied and even added the feature back! Thank you guys so much!

Also yeah I kinda get what you're saying @casperstorm, about the formatting and stuff, but at least to me personally, I'd rather have it work for 90% of the addons (in my experience anyway) than none. So thanks once again!
