### ISSUE TITLE
README: Linux install

### ISSUE THREAD

**Issue by WeaponMan** [casperstorm/ajour#56]
You can install ajour with `cargo install ajour --git https://github.com/casperstorm/ajour.git` if you have cargo and compile dependencies installed.
Would be great to publish the crate to crates.io, then you can ommit the --git part.

**Comment by casperstorm** [comment]
I think we should add a new section to the README explaining different ways of getting Ajour. This relates to #50.

**Comment by casperstorm** [comment]
I can't create a package right now, because `iced` is not bound to any version in [Cargo.toml](https://github.com/casperstorm/ajour/blob/master/Cargo.toml#L15-L16). When `iced` releases a new version with the features we dependent on, i'll create a crate and add the information to [INSTALL.md](https://github.com/casperstorm/ajour/blob/master/INSTALL.md).

**Comment by casperstorm** [comment]
Resolved in 579e17e347d06bd14dae8c0af6fc742626a86d2f
