### ISSUE TITLE
Updating addons and status reverts to "update" after I refresh

### ISSUE THREAD

**Issue by xaldron** [casperstorm/ajour#74]
Hello, 
Thank you for this great contribution. I've been looking for a good open source alternative to Twitch for a long time, and now seem to finally have found one. 

I'm encountering an issue where the app tells me that certain apps need an update. After I update said addons trough the app, the status reverts to "update" after I refresh or close the app and open it again. Any ideas what might cause the problem? I does seem like the addons are getting updated, just not the status in the app.

**Comment by mlablah** [comment]
Hello @xaldron. 

Thanks for reporting the issue.

This can happen if the version reported by the api, doesn't match the "## Version:" in the .toc file of the downloaded addon. If that happens Ajour will think that the addon is out of date and present the "Update" button again (unless the addon is manually ignored).

Can you tell us which of the addon(s) you are using that exhibit this behavior? 

We have a wiki page were we document [addons with known issues](https://github.com/casperstorm/ajour/wiki/Addons-with-known-issues), so that we can keep track of them. If certain types of errors are too prevalent, we might have to implement workarounds to handle them. So knowing which addons do this, is important to us. :)

**Comment by xaldron** [comment]
Hello Mlablah, and thanks for the quick response!
For retail I encounter the issue with the following addons: 
- Easy Scrap
- GladiatorloSA

For classic: 
- Atlas
- Wardrobe

Thanks again for an otherwise great addon manager! Do you have plans to add the feauture to also install addons from your app? :)

**Comment by mlablah** [comment]
I've taken a look at the listed addons. 

| addon | flavor | toc | api | explanation |
|-|-|-|-|-|
| Easy Scrap | retail | 24 | 25 | version in toc doesn't match api version |
| GladiatorLOSSA2 | retail | 2.3.2 | GSA2_2.3.2 | number "2" in addon name tricking ajour |
| Atlas | classic | v1.47.03.11304.00 | v1.47.03.11305 | version in toc doesn't match api version |
| Wardrobe | classic | 2.0.0 | Wardrobe-1.0.10 | version in toc doesn't match api version |

I'll add them to the list. 

@casperstorm 3 of 4 might have been prevented with a fingerprint comparison (if the algorithm for calculating it works). The last one (GladiatorLOSSA2) seems to have encountered a limitation of our version comparison logic. If the addon name itself contains a number AND is listed in the remote version, we interpret it as part of the version of the addon.
