### ISSUE TITLE
Set Path

### ISSUE THREAD

**Issue by mlablah** [casperstorm/ajour#8]
As a user I want to be able to specify the path to my Interface folder.

In the `Settings` menu, there should be an option to specify a path.

* Display input field to user (or allow user to navigate to folder)
* Write user specified path to config file
* Return to app main window

**Comment by casperstorm** [comment]
As referenced in #2 - `path` for the AddOns folder should be set in the [configuration file](https://github.com/casperstorm/ajour/blob/master/ajour.yml). The file is still WIP, but it should be working for version 1.0.

**Comment by m5r** [comment]
Can we make it auto-detect the path to the game ?

I just downloaded the Ajour 0.1.0 Beta 5 release on Windows and the app would constantly fail with the following error message: `Error reading ajour.yml file`.  
I fixed it by updating the `%APPDATA%\ajour\ajour.yml` file with the path to the WoW folder `C:/Program Files (x86)/World of Warcraft` and the `classic` flavor setting

**Comment by casperstorm** [comment]
> Can we make it auto-detect the path to the game ?
> 
> I just downloaded the Ajour 0.1.0 Beta 5 release on Windows and the app would constantly fail with the following error message: `Error reading ajour.yml file`.
> I fixed it by updating the `%APPDATA%\ajour\ajour.yml` file with the path to the WoW folder `C:/Program Files (x86)/World of Warcraft` and the `classic` flavor setting

Hey @m5r.
I don't want Ajour to auto-detect the game, because it isn't very privacy friendly. But with that said, I do 100% agree that it isn't very UX friendly that you have to edit the configuration file by hand. This will however be fixed when we merge #48 into master. We are slowly moving all the variables from the configuration file into the settings screen, so when version `1.0.0` hits you don't need it.
