### ISSUE TITLE
Add search and install

### ISSUE THREAD

**Issue by the-isz** [casperstorm/ajour#83]
**Is your feature request related to a problem? Please describe.**
It would be very convenient to install addons directly from ajour instead of having to install them manually once.

**Describe the solution you'd like**
Search feature:
1. Enter keywords
2. ajour searches curseforge and other addon pages for matching addons (names and descriptions)
3. ajour lists matches
4. Each match has an "Install" button to download and extract the respective addon

**Describe alternatives you've considered**
The alternative is to keep things as they are. Which is fine, too, just a little more inconvenient :D

**Comment by casperstorm** [comment]
This is planned! You can see the whole roadmap here: https://github.com/casperstorm/ajour/projects/2.
I want to get this right, but before starting I want to make sure parsing, fetching and dowloading addons is smooth as butter which is why feature set is limited to that for now.

I'll close this for now since you can read more in the roadmap, but please open new issues if you have problems, ideas or anything 🙏🏻
