### ISSUE TITLE
Able to select Release Type of Alpha or Beta when updating addons

### ISSUE THREAD

**Issue by mchris2** [casperstorm/ajour#92]
**Is your feature request related to a problem? Please describe.**
I prefer to install Alpha releases of addons (and as I have 185 addons installed it's not really feasible to do it individually). When an alpha version is released I install it, and then only revert to Beta or Release if there are issues found.

**Describe the solution you'd like**
Ability to select the release type of individual addons (e.g. DBM as alpha release, KuiNameplates as Release, Raven as Alpha)

**Describe alternatives you've considered**
N/A

**Comment by casperstorm** [comment]
Good point, and good use case @mchris2.
I actually know what type of release it is, so we could add a dropdown menu in the details section for each addon. This would of cause only work for addons found on CurseForge, and not TukUI because they only have 1 release channel.

This should be fairly straight forward to implement.

**Comment by mlablah** [comment]
@mchris2 Can you elaborate on the exact behavior your would expect from Ajour with this feature?
Say for example you select the "Beta" channel for Addon X. Would you then expect it to:
1) Always update to the latest beta version of the addon.
2) Update to the latest Beta OR Release version of the addon. Whichever is newest.

**Comment by mchris2** [comment]
@mlablah  Option 2 is the preferred one. So you always have the most recent version whether it is Alpha, Beta or Release.

**Comment by mlablah** [comment]
**Design proposal**
* Add a "Default update channel" option to settings. Possible values should be 3 of the file types supported by Curse: "Alpha", "Beta" and "Release" with the pre-selected value being "Release". 
* Allow the user to override the default update channel by choosing a different channel in the details view. e.g. a dropdown with options: "Default", "Release", "Beta", "Alpha".

Notes:
Alpha = find latest update from types: alpha, beta, release
Beta = find latest update from types: beta, release
Release = find latest update from types: release

Since only curse uses these file types, ignore them when calling other api's.

**Comment by mchris2** [comment]
@mlablah I like it
