### ISSUE TITLE
Thread panic at init when run from terminal in Manjaro Linux

### ISSUE THREAD

**Issue by nina-j** [casperstorm/ajour#95]
**Describe the bug**
Ajour tries to create a folder that already exists and emits a thread panic when run from the terminal under Manjaro KDE.
```sh
thread '<unnamed>' panicked at 'could not create folder $HOME/.config/ajour: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/fs/mod.rs:24:37
``` 

**To Reproduce**
1. Build ajour
2. Click on the binary in `target/release`
3. Have Dolphin tell you that executing binaries is not allowed for security reasons
4. Run from terminal instead `cd target/release/` -> `./ajour`

Note that this only happens the first time ajour is run in this manner, so I suspect something weird is happening during init. Also, it does not affect functionality, so I wouldn't call it serious. 

**Expected behavior**
No panics!

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/28903001/92990338-0578b280-f4dc-11ea-9047-68d752ee9391.png)

**Comment by casperstorm** [comment]
Thanks for reporting this @nina-j 
The issue seems to be that intially when Ajour is starting we are asking for the `config_dir` a few times. And some race condition is causing this behavior:  while creating the folder, someone else asks if the folder is created which it isn't hence it tries to create the folder and fails because by the time it's done someone else created it.

As you also said, the second time you open the app, it should be fine. I'll try to get it fixed ASAP.
Unrelated: funny it was only triggered on Linux, and not macOS.

**Comment by tarkah** [comment]
@nina-j Since it appears your building from source, can you test #95? Delete your .config/ajour folder first and then `cargo run --release` (this builds and runs it in one command instead of having to run it from `target/release`).

Thanks!

**Comment by tarkah** [comment]
I was able to test on my linux desktop. Previously I got the same panic when .config/ajour didn't exist on bootup. With #97 it no longer panics when .config/ajour doesn't exist on bootup.
